project_id = "gtcgflogcxqwpgcnkocf"

[functions.execute-code]
verify_jwt = false

[functions.session-management]
verify_jwt = false

[functions.admin-warnings]
verify_jwt = false

[functions.report-violation]
verify_jwt = false
